Repository openAOD/CPlusPlus-PatternHouse, pull requests merged in 2021-12, with the labels that each got.

#763 added alphabet pattern 32
  Alphabetic Patterns/alphabeticpattern32.cpp
  Alphabetic Patterns/alphabeticpattern33.cpp
Labels: SWoC-21

#764 Symbol Patterns
  Symbol Patterns/symbolpattern21.cpp
  Symbol Patterns/symbolpattern22.cpp
  Symbol Patterns/symbolpattern23.cpp
  Symbol Patterns/symbolpattern24.cpp
  Symbol Patterns/symbolpattern26.cpp
  Symbol Patterns/symbolpattern27.cpp
  Symbol Patterns/symbolpattern37.cpp
  Symbol Patterns/symbolpattern38.cpp
  Symbol Patterns/symbolpattern39.cpp
  Symbol Patterns/symbolpattern40.cpp
  Symbol Patterns/symbolpattern41.cpp
  Symbol Patterns/symbolpattern42.cpp
Labels: SWoC-21

#765 Symbol Patterns48
  Symbol Patterns/symbolpattern48.cpp
Labels: SWoC-21

#766 Code for Numeric Pattern 287
  numericpattern287.cpp
  numericpattern288.cpp
Labels: SWoC-21

#767 SymbolPattern (1-5) added
  Symbol Patterns/symbolpattern1.cpp
  Symbol Patterns/symbolpattern2.cpp
  Symbol Patterns/symbolpattern3.cpp
  Symbol Patterns/symbolpattern4.cpp
  Symbol Patterns/symbolpattern5.cpp
Labels: SWoC-21

#768 Series Pattern 1 to 5
  Series Patterns/seriespattern1.cpp
  Series Patterns/seriespattern2.cpp
  Series Patterns/seriespattern3.cpp
  Series Patterns/seriespattern4.cpp
  Series Patterns/seriespattern5.cpp
Labels: SWoC-21

#769 symbolpattern added
  Symbol Patterns/symbolpattern12.cpp
  Symbol Patterns/symbolpattern13.cpp
  Symbol Patterns/symbolpattern14.cpp
  Symbol Patterns/symbolpattern15.cpp
  Symbol Patterns/symbolpattern16.cpp
Labels: SWoC-21

#770 Added symbol-patterns
  Symbol Patterns/symbolpattern6.cpp
  Symbol Patterns/symbolpattern7.cpp
Labels: SWoC-21

#771 solved issue #345
  Alphabetic Patterns/alphabeticpattern185.cpp
  Numeric Patterns/numericpattern36.cpp
Labels: SWoC-21

#772 Alphabetic pattern 34-41(cpp)
  Alphabetic Patterns/alphabeticpattern34.cpp
  Alphabetic Patterns/alphabeticpattern35.cpp
  Alphabetic Patterns/alphabeticpattern36.cpp
  Alphabetic Patterns/alphabeticpattern37.cpp
  Alphabetic Patterns/alphabeticpattern38.cpp
  Alphabetic Patterns/alphabeticpattern39.cpp
  Alphabetic Patterns/alphabeticpattern40.cpp
  Alphabetic Patterns/alphabeticpattern41.cpp
Labels: SWoC-21

#773 Solved issue #345
  Alphabetic Patterns/alphabeticpattern186.cpp
Labels: SWoC-21

#774 Added code for Symbol Pattern 45.
  Symbol Patterns/symbolpattern45.cpp
Labels: SWoC-21

#776 Added code for Symbol Pattern 18.
  Symbol Patterns/symbolpattern18.cpp
  Symbol Patterns/symbolpattern45.cpp
Labels: SWoC-21

#778 Added code for symbol pattern 20.
  Symbol Patterns/symbolpattern20.cpp
Labels: SWoC-21

#777 Added code for Symbol Pattern 19
  Symbol Patterns/symbolpattern19.cpp
Labels: SWoC-21

#779 Added code for symbol pattern 25.
  Symbol Patterns/symbolpattern25.cpp
Labels: SWoC-21

#780 Added code for symbol pattern 28.
  Symbol Patterns/symbolpattern28.cpp
Labels: SWoC-21

#781 Added code for symbol pattern 29.
  Symbol Patterns/symbolpattern29.cpp
Labels: SWoC-21

#782 Added code for symbol pattern 30.
  Symbol Patterns/symbolpattern30.cpp
Labels: SWoC-21

#785 Added code for Pattern 31 to 47.
  Symbol Patterns/symbolpattern31.cpp
  Symbol Patterns/symbolpattern32.cpp
  Symbol Patterns/symbolpattern33.cpp
  Symbol Patterns/symbolpattern34.cpp
  Symbol Patterns/symbolpattern35.cpp
  Symbol Patterns/symbolpattern36.cpp
  Symbol Patterns/symbolpattern43.cpp
  Symbol Patterns/symbolpattern44.cpp
  Symbol Patterns/symbolpattern46.cpp
  Symbol Patterns/symbolpattern47.cpp
Labels: SWoC-21, beginner

#784 Added 10 Pattern Codes
  Numeric Patterns/numericpattern286.cpp
  String Patterns/stringpattern10.cpp
  String Patterns/stringpattern11.cpp
  String Patterns/stringpattern12.cpp
  String Patterns/stringpattern13.cpp
  String Patterns/stringpattern14.cpp
  String Patterns/stringpattern15.cpp
  String Patterns/stringpattern4.cpp
  String Patterns/stringpattern5.cpp
  String Patterns/stringpattern6.cpp
  String Patterns/stringpattern7.cpp
  String Patterns/stringpattern8.cpp
  String Patterns/stringpattern9.cpp
  Wave Patterns/wavepattern1.cpp
  Wave Patterns/wavepattern3.cpp
  Wave Patterns/wavepattern4.cpp
  Wave Patterns/wavepattern5.cpp
  Wave Patterns/wavepattern6.cpp
  Wave Patterns/wavepattern7.cpp
  Wave Patterns/wavepattern8.cpp
Labels: SWoC-21, easy

#786 Solved issue #300
  Alphabetic Patterns/alphabeticpattern140.cpp
  Alphabetic Patterns/alphabeticpattern141.cpp
  Alphabetic Patterns/alphabeticpattern142.cpp
  Alphabetic Patterns/alphabeticpattern143.cpp
  Alphabetic Patterns/alphabeticpattern144.cpp
  Alphabetic Patterns/alphabeticpattern166.cpp
  Alphabetic Patterns/alphabeticpattern167.cpp
  Alphabetic Patterns/alphabeticpattern168.cpp
  Alphabetic Patterns/alphabeticpattern169.cpp
  Alphabetic Patterns/alphabeticpattern170.cpp
Labels: SWoC-21, beginner

#787 numericpattern180-190 added
  Numeric Patterns/numericpattern180.cpp
  Numeric Patterns/numericpattern181.cpp
  Numeric Patterns/numericpattern182.cpp
  Numeric Patterns/numericpattern183.cpp
  Numeric Patterns/numericpattern184.cpp
  Numeric Patterns/numericpattern185.cpp
  Numeric Patterns/numericpattern186.cpp
  Numeric Patterns/numericpattern187.cpp
  Numeric Patterns/numericpattern188.cpp
  Numeric Patterns/numericpattern189.cpp
  Numeric Patterns/numericpattern190.cpp
Labels: SWoC-21, beginner

#788 Added Numeric Pattern 101-120
  Numeric Patterns/numericpattern101.cpp
  Numeric Patterns/numericpattern102.cpp
  Numeric Patterns/numericpattern103.cpp
  Numeric Patterns/numericpattern104.cpp
  Numeric Patterns/numericpattern105.cpp
  Numeric Patterns/numericpattern106.cpp
  Numeric Patterns/numericpattern107.cpp
  Numeric Patterns/numericpattern108.cpp
  Numeric Patterns/numericpattern109.cpp
  Numeric Patterns/numericpattern110.cpp
  Numeric Patterns/numericpattern111.cpp
  Numeric Patterns/numericpattern112.cpp
  Numeric Patterns/numericpattern113.cpp
  Numeric Patterns/numericpattern114.cpp
  Numeric Patterns/numericpattern115.cpp
  Numeric Patterns/numericpattern116.cpp
  Numeric Patterns/numericpattern117.cpp
  Numeric Patterns/numericpattern118.cpp
  Numeric Patterns/numericpattern119.cpp
  Numeric Patterns/numericpattern120.cpp
Labels: SWoC-21, easy

#791 Added code for symbol pattern from 49 to 60.
  Symbol Patterns/symbolpattern49.cpp
  Symbol Patterns/symbolpattern51.cpp
  Symbol Patterns/symbolpattern52.cpp
  Symbol Patterns/symbolpattern53.cpp
  Symbol Patterns/symbolpattern54.cpp
  Symbol Patterns/symbolpattern55.cpp
  Symbol Patterns/symbolpattern56.cpp
  Symbol Patterns/symbolpattern57.cpp
  Symbol Patterns/symbolpattern58.cpp
  Symbol Patterns/symbolpattern59.cpp
  Symbol Patterns/symbolpattern60.cpp
Labels: SWoC-21, beginner

#939 20 patterns (48-57, 65-74) added
  Numeric Patterns/numericpattern48.cpp
  Numeric Patterns/numericpattern49.cpp
  Numeric Patterns/numericpattern50.cpp
  Numeric Patterns/numericpattern51.cpp
  Numeric Patterns/numericpattern52.cpp
  Numeric Patterns/numericpattern53.cpp
  Numeric Patterns/numericpattern54.cpp
  Numeric Patterns/numericpattern55.cpp
  Numeric Patterns/numericpattern56.cpp
  Numeric Patterns/numericpattern57.cpp
  Numeric Patterns/numericpattern65.cpp
  Numeric Patterns/numericpattern66.cpp
  Numeric Patterns/numericpattern67.cpp
  Numeric Patterns/numericpattern68.cpp
  Numeric Patterns/numericpattern69.cpp
  Numeric Patterns/numericpattern70.cpp
  Numeric Patterns/numericpattern71.cpp
  Numeric Patterns/numericpattern72.cpp
  Numeric Patterns/numericpattern73.cpp
  Numeric Patterns/numreicpattern74.cpp
Labels: SWoC-21, easy

#790 Added symbol patterns
  Spiral Patterns/spiralpattern1.cpp
  Spiral Patterns/spiralpattern3.cpp
  Spiral Patterns/spiralpattern4.cpp
  Symbol Patterns/symbolpattern10.cpp
  Symbol Patterns/symbolpattern11.cpp
  Symbol Patterns/symbolpattern71.cpp
  Symbol Patterns/symbolpattern72.cpp
  Symbol Patterns/symbolpattern73.cpp
  Symbol Patterns/symbolpattern74.cpp
  Symbol Patterns/symbolpattern75.cpp
  Symbol Patterns/symbolpattern79.cpp
  Symbol Patterns/symbolpattern8.cpp
  Symbol Patterns/symbolpattern9.cpp
Labels: SWoC-21, easy

#792 Solved issue #346
  Alphabetic Patterns/alphabeticpattern146.cpp
  Alphabetic Patterns/alphabeticpattern147.cpp
  Alphabetic Patterns/alphabeticpattern148.cpp
  Alphabetic Patterns/alphabeticpattern149.cpp
  Alphabetic Patterns/alphabeticpattern150.cpp
  Alphabetic Patterns/alphabeticpattern172.cpp
  Alphabetic Patterns/alphabeticpattern173.cpp
  Alphabetic Patterns/alphabeticpattern174.cpp
  Alphabetic Patterns/alphabeticpattern175.cpp
  Alphabetic Patterns/alphabeticpattern176.cpp
Labels: SWoC-21, beginner

#941 Added code for pyramid pattern from 1 to 20.
  Pyramid Patterns/pyramidpattern1.cpp
  Pyramid Patterns/pyramidpattern10.cpp
  Pyramid Patterns/pyramidpattern11.cpp
  Pyramid Patterns/pyramidpattern12.cpp
  Pyramid Patterns/pyramidpattern13.cpp
  Pyramid Patterns/pyramidpattern14.cpp
  Pyramid Patterns/pyramidpattern15.cpp
  Pyramid Patterns/pyramidpattern16.cpp
  Pyramid Patterns/pyramidpattern17.cpp
  Pyramid Patterns/pyramidpattern18.cpp
  Pyramid Patterns/pyramidpattern19.cpp
  Pyramid Patterns/pyramidpattern2.cpp
  Pyramid Patterns/pyramidpattern20.cpp
  Pyramid Patterns/pyramidpattern3.cpp
  Pyramid Patterns/pyramidpattern4.cpp
  Pyramid Patterns/pyramidpattern5.cpp
  Pyramid Patterns/pyramidpattern6.cpp
  Pyramid Patterns/pyramidpattern7.cpp
  Pyramid Patterns/pyramidpattern8.cpp
  Pyramid Patterns/pyramidpattern9.cpp
Labels: SWoC-21, easy

#942 Added 20 symbol patterns
  Symbol Patterns/symbolpattern102.cpp
  Symbol Patterns/symbolpattern103.cpp
  Symbol Patterns/symbolpattern104.cpp
  Symbol Patterns/symbolpattern105.cpp
  Symbol Patterns/symbolpattern106.cpp
  Symbol Patterns/symbolpattern76.cpp
  Symbol Patterns/symbolpattern77.cpp
  Symbol Patterns/symbolpattern80.cpp
  Symbol Patterns/symbolpattern81.cpp
  Symbol Patterns/symbolpattern82.cpp
  Symbol Patterns/symbolpattern83.cpp
  Symbol Patterns/symbolpattern84.cpp
  Symbol Patterns/symbolpattern85.cpp
  Symbol Patterns/symbolpattern86.cpp
  Symbol Patterns/symbolpattern87.cpp
  Symbol Patterns/symbolpattern88.cpp
  Symbol Patterns/symbolpattern89.cpp
  Symbol Patterns/symbolpattern90.cpp
  Symbol Patterns/symbolpattern93.cpp
  Symbol Patterns/symbolpattern94.cpp
Labels: SWoC-21, easy

#940 10 patterns added
  Numeric Patterns/numericpattern17.cpp
  Numeric Patterns/numericpattern18.cpp
  Numeric Patterns/numericpattern19.cpp
  Numeric Patterns/numericpattern20.cpp
  Numeric Patterns/numericpattern29.cpp
  Numeric Patterns/numericpattern31.cpp
  Numeric Patterns/numericpattern32.cpp
  Numeric Patterns/numericpattern58.cpp
  Numeric Patterns/numericpattern59.cpp
  Numeric Patterns/numericpattern60.cpp
Labels: SWoC-21, beginner

#943 Added 20 wave patterns
  Wave Patterns/wavepattern10.cpp
  Wave Patterns/wavepattern11.cpp
  Wave Patterns/wavepattern12.cpp
  Wave Patterns/wavepattern13.cpp
  Wave Patterns/wavepattern14.cpp
  Wave Patterns/wavepattern15.cpp
  Wave Patterns/wavepattern16.cpp
  Wave Patterns/wavepattern17.cpp
  Wave Patterns/wavepattern18.cpp
  Wave Patterns/wavepattern19.cpp
  Wave Patterns/wavepattern2.cpp
  Wave Patterns/wavepattern20.cpp
  Wave Patterns/wavepattern21.cpp
  Wave Patterns/wavepattern22.cpp
  Wave Patterns/wavepattern23.cpp
  Wave Patterns/wavepattern24.cpp
  Wave Patterns/wavepattern25.cpp
  Wave Patterns/wavepattern26.cpp
  Wave Patterns/wavepattern27.cpp
  Wave Patterns/wavepattern9.cpp
Labels: SWoC-21, easy

#944 10 patterns added
  Numeric Patterns/numericpattern37.cpp
  Numeric Patterns/numericpattern38.cpp
  Numeric Patterns/numericpattern39.cpp
  Numeric Patterns/numericpattern40.cpp
  Numeric Patterns/numericpattern41.cpp
  Numeric Patterns/numericpattern42.cpp
  Numeric Patterns/numericpattern43.cpp
  Numeric Patterns/numericpattern44.cpp
  Numeric Patterns/numericpattern45.cpp
  Numeric Patterns/numericpattern46.cpp
Labels: SWoC-21, beginner

#946 Added 40 symbol patterns
  Symbol Patterns/symbolpattern100.cpp
  Symbol Patterns/symbolpattern101.cpp
  Symbol Patterns/symbolpattern107.cpp
  Symbol Patterns/symbolpattern108.cpp
  Symbol Patterns/symbolpattern109.cpp
  Symbol Patterns/symbolpattern110.cpp
  Symbol Patterns/symbolpattern111.cpp
  Symbol Patterns/symbolpattern112.cpp
  Symbol Patterns/symbolpattern113.cpp
  Symbol Patterns/symbolpattern114.cpp
  Symbol Patterns/symbolpattern115.cpp
  Symbol Patterns/symbolpattern116.cpp
  Symbol Patterns/symbolpattern117.cpp
  Symbol Patterns/symbolpattern118.cpp
  Symbol Patterns/symbolpattern119.cpp
  Symbol Patterns/symbolpattern120.cpp
  Symbol Patterns/symbolpattern121.cpp
  Symbol Patterns/symbolpattern122.cpp
  Symbol Patterns/symbolpattern123.cpp
  Symbol Patterns/symbolpattern124.cpp
  Symbol Patterns/symbolpattern125.cpp
  Symbol Patterns/symbolpattern126.cpp
  Symbol Patterns/symbolpattern127.cpp
  Symbol Patterns/symbolpattern128.cpp
  Symbol Patterns/symbolpattern129.cpp
  Symbol Patterns/symbolpattern130.cpp
  Symbol Patterns/symbolpattern131.cpp
  Symbol Patterns/symbolpattern132.cpp
  Symbol Patterns/symbolpattern133.cpp
  Symbol Patterns/symbolpattern134.cpp
  Symbol Patterns/symbolpattern135.cpp
  Symbol Patterns/symbolpattern136.cpp
  Symbol Patterns/symbolpattern78.cpp
  Symbol Patterns/symbolpattern91.cpp
  Symbol Patterns/symbolpattern92.cpp
  Symbol Patterns/symbolpattern95.cpp
  Symbol Patterns/symbolpattern96.cpp
  Symbol Patterns/symbolpattern97.cpp
  Symbol Patterns/symbolpattern98.cpp
  Symbol Patterns/symbolpattern99.cpp
Labels: SWoC-21, hard

#947 20 patterns added
  Numeric Patterns/numericpattern61.cpp
  Numeric Patterns/numericpattern62.cpp
  Numeric Patterns/numericpattern75.cpp
  Numeric Patterns/numericpattern76.cpp
  Numeric Patterns/numericpattern77.cpp
  Numeric Patterns/numericpattern78.cpp
  Numeric Patterns/numericpattern79.cpp
  Numeric Patterns/numericpattern80.cpp
  Numeric Patterns/numericpattern81.cpp
  Numeric Patterns/numericpattern82.cpp
  Numeric Patterns/numericpattern87.cpp
  Numeric Patterns/numericpattern88.cpp
  Numeric Patterns/numericpattern89.cpp
  Numeric Patterns/numericpattern90.cpp
  Numeric Patterns/numericpattern91.cpp
  Numeric Patterns/numericpattern92.cpp
  Numeric Patterns/numericpattern93.cpp
  Numeric Patterns/numericpattern94.cpp
  Numeric Patterns/numericpattern95.cpp
  Numeric Patterns/numericpattern96.cpp
Labels: SWoC-21, easy

#948 Added code for pyramid pattern from 21 to 50.
  Pyramid Patterns/pyramidpattern21.cpp
  Pyramid Patterns/pyramidpattern22.cpp
  Pyramid Patterns/pyramidpattern23.cpp
  Pyramid Patterns/pyramidpattern24.cpp
  Pyramid Patterns/pyramidpattern25.cpp
  Pyramid Patterns/pyramidpattern26.cpp
  Pyramid Patterns/pyramidpattern27.cpp
  Pyramid Patterns/pyramidpattern28.cpp
  Pyramid Patterns/pyramidpattern29.cpp
  Pyramid Patterns/pyramidpattern30.cpp
  Pyramid Patterns/pyramidpattern31.cpp
  Pyramid Patterns/pyramidpattern32.cpp
  Pyramid Patterns/pyramidpattern33.cpp
  Pyramid Patterns/pyramidpattern34.cpp
  Pyramid Patterns/pyramidpattern35.cpp
  Pyramid Patterns/pyramidpattern36.cpp
  Pyramid Patterns/pyramidpattern37.cpp
  Pyramid Patterns/pyramidpattern38.cpp
  Pyramid Patterns/pyramidpattern39.cpp
  Pyramid Patterns/pyramidpattern40.cpp
  Pyramid Patterns/pyramidpattern41.cpp
  Pyramid Patterns/pyramidpattern42.cpp
  Pyramid Patterns/pyramidpattern43.cpp
  Pyramid Patterns/pyramidpattern44.cpp
  Pyramid Patterns/pyramidpattern45.cpp
  Pyramid Patterns/pyramidpattern46.cpp
  Pyramid Patterns/pyramidpattern47.cpp
  Pyramid Patterns/pyramidpattern48.cpp
  Pyramid Patterns/pyramidpattern49.cpp
  Pyramid Patterns/pyramidpattern50.cpp
Labels: SWoC-21, medium

#949 Fixes all issues from #793 to #802
  Symbol Patterns/symbolpattern61.cpp
  Symbol Patterns/symbolpattern62.cpp
  Symbol Patterns/symbolpattern63.cpp
  Symbol Patterns/symbolpattern64.cpp
  Symbol Patterns/symbolpattern65.cpp
  Symbol Patterns/symbolpattern66.cpp
  Symbol Patterns/symbolpattern67.cpp
  Symbol Patterns/symbolpattern68.cpp
  Symbol Patterns/symbolpattern69.cpp
  Symbol Patterns/symbolpattern70.cpp
Labels: SWoC-21, beginner

#950 Added code for pyramid pattern from 51 to 70.
  Pyramid Patterns/pyramidpattern51.cpp
  Pyramid Patterns/pyramidpattern52.cpp
  Pyramid Patterns/pyramidpattern53.cpp
  Pyramid Patterns/pyramidpattern54.cpp
  Pyramid Patterns/pyramidpattern55.cpp
  Pyramid Patterns/pyramidpattern56.cpp
  Pyramid Patterns/pyramidpattern57.cpp
  Pyramid Patterns/pyramidpattern58.cpp
  Pyramid Patterns/pyramidpattern59.cpp
  Pyramid Patterns/pyramidpattern60.cpp
  Pyramid Patterns/pyramidpattern61.cpp
  Pyramid Patterns/pyramidpattern62.cpp
  Pyramid Patterns/pyramidpattern63.cpp
  Pyramid Patterns/pyramidpattern64.cpp
  Pyramid Patterns/pyramidpattern65.cpp
  Pyramid Patterns/pyramidpattern66.cpp
  Pyramid Patterns/pyramidpattern67.cpp
  Pyramid Patterns/pyramidpattern68.cpp
  Pyramid Patterns/pyramidpattern69.cpp
  Pyramid Patterns/pyramidpattern70.cpp
Labels: SWoC-21, easy

#951 30 patterns added
  Numeric Patterns/numericpattern12.cpp
  Numeric Patterns/numericpattern13.cpp
  Numeric Patterns/numericpattern14.cpp
  Numeric Patterns/numericpattern15.cpp
  Numeric Patterns/numericpattern16.cpp
  Numeric Patterns/numericpattern163.cpp
  Numeric Patterns/numericpattern164.cpp
  Numeric Patterns/numericpattern165.cpp
  Numeric Patterns/numericpattern166.cpp
  Numeric Patterns/numericpattern170.cpp
  Numeric Patterns/numericpattern171.cpp
  Numeric Patterns/numericpattern175.cpp
  Numeric Patterns/numericpattern176.cpp
  Numeric Patterns/numericpattern192.cpp
  Numeric Patterns/numericpattern193.cpp
  Numeric Patterns/numericpattern194.cpp
  Numeric Patterns/numericpattern195.cpp
  Numeric Patterns/numericpattern196.cpp
  Numeric Patterns/numericpattern197.cpp
  Numeric Patterns/numericpattern198.cpp
  Numeric Patterns/numericpattern199.cpp
  Numeric Patterns/numericpattern200.cpp
  Numeric Patterns/numericpattern201.cpp
  Numeric Patterns/numericpattern3.cpp
  Numeric Patterns/numericpattern63.cpp
  Numeric Patterns/numericpattern64.cpp
  Numeric Patterns/numericpattern8.cpp
  Numeric Patterns/numericpattern97.cpp
  Numeric Patterns/numericpattern98.cpp
  Numeric Patterns/numericpattern99.cpp
Labels: SWoC-21, medium

#952 Added code for pyramid pattern from 71 to 93.
  Pyramid Patterns/pyramidpattern71.cpp
  Pyramid Patterns/pyramidpattern72.cpp
  Pyramid Patterns/pyramidpattern73.cpp
  Pyramid Patterns/pyramidpattern74.cpp
  Pyramid Patterns/pyramidpattern75.cpp
  Pyramid Patterns/pyramidpattern76.cpp
  Pyramid Patterns/pyramidpattern77.cpp
  Pyramid Patterns/pyramidpattern78.cpp
  Pyramid Patterns/pyramidpattern79.cpp
  Pyramid Patterns/pyramidpattern80.cpp
  Pyramid Patterns/pyramidpattern81.cpp
  Pyramid Patterns/pyramidpattern82.cpp
  Pyramid Patterns/pyramidpattern83.cpp
  Pyramid Patterns/pyramidpattern84.cpp
  Pyramid Patterns/pyramidpattern85.cpp
  Pyramid Patterns/pyramidpattern86.cpp
  Pyramid Patterns/pyramidpattern87.cpp
  Pyramid Patterns/pyramidpattern88.cpp
  Pyramid Patterns/pyramidpattern89.cpp
  Pyramid Patterns/pyramidpattern90.cpp
  Pyramid Patterns/pyramidpattern91.cpp
  Pyramid Patterns/pyramidpattern92.cpp
  Pyramid Patterns/pyramidpattern93.cpp
Labels: SWoC-21, easy

#953 30 patterns added
  Alphabetic Patterns/alphabeticpattern58.cpp
  Alphabetic Patterns/alphabeticpattern59.cpp
  Alphabetic Patterns/alphabeticpattern60.cpp
  Alphabetic Patterns/alphabeticpattern61.cpp
  Alphabetic Patterns/alphabeticpattern62.cpp
  Alphabetic Patterns/alphabeticpattern63.cpp
  Alphabetic Patterns/alphabeticpattern64.cpp
  Alphabetic Patterns/alphabeticpattern65.cpp
  Alphabetic Patterns/alphabeticpattern72.cpp
  Alphabetic Patterns/alphabeticpattern73.cpp
  Alphabetic Patterns/alphabeticpattern74.cpp
  Alphabetic Patterns/alphabeticpattern75.cpp
  Alphabetic Patterns/alphabeticpattern76.cpp
  Alphabetic Patterns/alphabeticpattern77.cpp
  Alphabetic Patterns/alphabeticpattern78.cpp
  Alphabetic Patterns/alphabeticpattern79.cpp
  Alphabetic Patterns/alphabeticpattern80.cpp
  Alphabetic Patterns/alphabeticpattern81.cpp
  Alphabetic Patterns/alphabeticpattern82.cpp
  Alphabetic Patterns/alphabeticpattern83.cpp
  Alphabetic Patterns/alphabeticpattern84.cpp
  Alphabetic Patterns/alphabeticpattern85.cpp
  Alphabetic Patterns/alphabeticpattern86.cpp
  Alphabetic Patterns/alphabeticpattern87.cpp
  Alphabetic Patterns/alphabeticpattern88.cpp
  Alphabetic Patterns/alphabeticpattern89.cpp
  Alphabetic Patterns/alphabeticpattern90.cpp
  Alphabetic Patterns/alphabeticpattern91.cpp
  Alphabetic Patterns/alphabeticpattern92.cpp
  Alphabetic Patterns/alphabeticpattern93.cpp
Labels: SWoC-21, medium

#954 Added 10 patterns
  Spiral Patterns/spiralpattern2.cpp
  String Patterns/stringpattern1.cpp
  String Patterns/stringpattern2.cpp
  String Patterns/stringpattern3.cpp
  Symbol Patterns/symbolpattern140.cpp
  Symbol Patterns/symbolpattern141.cpp
  Symbol Patterns/symbolpattern152.cpp
  Symbol Patterns/symbolpattern171.cpp
  Symbol Patterns/symbolpattern173.cpp
  Symbol Patterns/symbolpttern142.cpp
Labels: SWoC-21, beginner

#955 Anshyyy
  Alphabetic Patterns/alphabeticpattern151.cpp
  Alphabetic Patterns/alphabeticpattern152.cpp
  Alphabetic Patterns/alphabeticpattern153.cpp
  Alphabetic Patterns/alphabeticpattern154.cpp
  Alphabetic Patterns/alphabeticpattern155.cpp
  Alphabetic Patterns/alphabeticpattern177.cpp
  Alphabetic Patterns/alphabeticpattern178.cpp
  Alphabetic Patterns/alphabeticpattern179.cpp
  Alphabetic Patterns/alphabeticpattern180.cpp
  Alphabetic Patterns/alphabeticpattern181.cpp
Labels: SWoC-21, beginner

#956 10 patterns added
  Alphabetic Patterns/alphabeticpattern134.cpp
  Alphabetic Patterns/alphabeticpattern135.cpp
  Alphabetic Patterns/alphabeticpattern136.cpp
  Alphabetic Patterns/alphabeticpattern137.cpp
  Alphabetic Patterns/alphabeticpattern138.cpp
  Alphabetic Patterns/alphabeticpattern139.cpp
  Alphabetic Patterns/alphabeticpattern70.cpp
  Alphabetic Patterns/alphabeticpattern94.cpp
  Alphabetic Patterns/alphabeticpattern95.cpp
  Alphabetic Patterns/alphabeticpattern96.cpp
Labels: SWoC-21, beginner

#958 20 numeric patterns added
  Numeric Patterns/numericpattern10.cpp
  Numeric Patterns/numericpattern100.cpp
  Numeric Patterns/numericpattern167.cpp
  Numeric Patterns/numericpattern168.cpp
  Numeric Patterns/numericpattern169.cpp
  Numeric Patterns/numericpattern172.cpp
  Numeric Patterns/numericpattern173.cpp
  Numeric Patterns/numericpattern174.cpp
  Numeric Patterns/numericpattern177.cpp
  Numeric Patterns/numericpattern178.cpp
  Numeric Patterns/numericpattern179.cpp
  Numeric Patterns/numericpattern191.cpp
  Numeric Patterns/numericpattern202.cpp
  Numeric Patterns/numericpattern203.cpp
  Numeric Patterns/numericpattern47.cpp
  Numeric Patterns/numericpattern83.cpp
  Numeric Patterns/numericpattern84.cpp
  Numeric Patterns/numericpattern85.cpp
  Numeric Patterns/numericpattern86.cpp
  Numeric Patterns/numericpattern9.cpp
Labels: SWoC-21, easy
