Repository openAOD/CPlusPlus-PatternHouse, pull requests merged in 2022-01, with the labels that each got.

#960 Alphabetic pattern 145 AND Numeric pattern 233,237,245,246,311,321,322
  Alphabetic Patterns/alphabeticpattern145.cpp
  Numeric Patterns/numericpattern232.cpp
  Numeric Patterns/numericpattern233.cpp
  Numeric Patterns/numericpattern237.cpp
  Numeric Patterns/numericpattern245.cpp
  Numeric Patterns/numericpattern246.cpp
  Numeric Patterns/numericpattern251.cpp
  Numeric Patterns/numericpattern311.cpp
  Numeric Patterns/numericpattern321.cpp
  Numeric Patterns/numericpattern322.cpp
Labels: SWoC-21, beginner

#964 20 patterns added Numeric and Alphabetic
  Alphabetic Patterns/alphabeticpattern101.cpp
  Alphabetic Patterns/alphabeticpattern102.cpp
  Alphabetic Patterns/alphabeticpattern103.cpp
  Alphabetic Patterns/alphabeticpattern104.cpp
  Alphabetic Patterns/alphabeticpattern105.cpp
  Alphabetic Patterns/alphabeticpattern106.cpp
  Alphabetic Patterns/alphabeticpattern107.cpp
  Alphabetic Patterns/alphabeticpattern108.cpp
  Alphabetic Patterns/alphabeticpattern109.cpp
  Alphabetic Patterns/alphabeticpattern110.cpp
  Numeric Patterns/numericpattern260.cpp
  Numeric Patterns/numericpattern261.cpp
  Numeric Patterns/numericpattern262.cpp
  Numeric Patterns/numericpattern263.cpp
  Numeric Patterns/numericpattern271.cpp
  Numeric Patterns/numericpattern272.cpp
  Numeric Patterns/numericpattern273.cpp
  Numeric Patterns/numericpattern283.cpp
  Numeric Patterns/numericpattern317.cpp
  Numeric Patterns/numericpattern318.cpp
Labels: SWoC-21, easy

#962 30 numeric patterns added
  Numeric Patterns/numericpattern204.cpp
  Numeric Patterns/numericpattern205.cpp
  Numeric Patterns/numericpattern206.cpp
  Numeric Patterns/numericpattern207.cpp
  Numeric Patterns/numericpattern208.cpp
  Numeric Patterns/numericpattern209.cpp
  Numeric Patterns/numericpattern210.cpp
  Numeric Patterns/numericpattern211.cpp
  Numeric Patterns/numericpattern212.cpp
  Numeric Patterns/numericpattern213.cpp
  Numeric Patterns/numericpattern214.cpp
  Numeric Patterns/numericpattern215.cpp
  Numeric Patterns/numericpattern216.cpp
  Numeric Patterns/numericpattern217.cpp
  Numeric Patterns/numericpattern218.cpp
  Numeric Patterns/numericpattern219.cpp
  Numeric Patterns/numericpattern220.cpp
  Numeric Patterns/numericpattern221.cpp
  Numeric Patterns/numericpattern222.cpp
  Numeric Patterns/numericpattern223.cpp
  Numeric Patterns/numericpattern224.cpp
  Numeric Patterns/numericpattern247.cpp
  Numeric Patterns/numericpattern248.cpp
  Numeric Patterns/numericpattern249.cpp
  Numeric Patterns/numericpattern250.cpp
  Numeric Patterns/numericpattern252.cpp
  Numeric Patterns/numericpattern253.cpp
  Numeric Patterns/numericpattern254.cpp
  Numeric Patterns/numericpattern255.cpp
  Numeric Patterns/numericpattern256.cpp
Labels: SWoC-21, medium

#957 Anshyyy
  Alphabetic Patterns/alphabeticpattern156.cpp
  Alphabetic Patterns/alphabeticpattern157.cpp
  Alphabetic Patterns/alphabeticpattern158.cpp
  Alphabetic Patterns/alphabeticpattern159.cpp
  Alphabetic Patterns/alphabeticpattern160.cpp
  Alphabetic Patterns/alphabeticpattern161.cpp
  Alphabetic Patterns/alphabeticpattern162.cpp
  Alphabetic Patterns/alphabeticpattern163.cpp
  Alphabetic Patterns/alphabeticpattern164.cpp
  Alphabetic Patterns/alphabeticpattern165.cpp
  Alphabetic Patterns/alphabeticpattern182.cpp
  Alphabetic Patterns/alphabeticpattern183.cpp
  Alphabetic Patterns/alphabeticpattern184.cpp
  Alphabetic Patterns/alphabeticpattern187.cpp
  Alphabetic Patterns/alphabeticpattern188.cpp
  Alphabetic Patterns/alphabeticpattern189.cpp
  Alphabetic Patterns/alphabeticpattern190.cpp
  Alphabetic Patterns/alphabeticpattern191.cpp
  Numeric Patterns/numericpattern314.cpp
  Numeric Patterns/numericpattern324.cpp
Labels: SWoC-21, easy

#961 Code for Numeric pattern 225 - 231, 234 - 236, 238 - 244.
  Alphabetic Patterns/alphabeticpattern100.cpp
  Alphabetic Patterns/alphabeticpattern97.cpp
  Alphabetic Patterns/alphabeticpattern98.cpp
  Alphabetic Patterns/alphabeticpattern99.cpp
  Numeric Patterns/numericpattern225.cpp
  Numeric Patterns/numericpattern226.cpp
  Numeric Patterns/numericpattern227.java
  Numeric Patterns/numericpattern228.cpp
  Numeric Patterns/numericpattern229.cpp
  Numeric Patterns/numericpattern230.cpp
  Numeric Patterns/numericpattern231.cpp
  Numeric Patterns/numericpattern234.cpp
  Numeric Patterns/numericpattern235.cpp
  Numeric Patterns/numericpattern236.cpp
  Numeric Patterns/numericpattern238.cpp
  Numeric Patterns/numericpattern239.cpp
  Numeric Patterns/numericpattern240.cpp
  Numeric Patterns/numericpattern241.cpp
  Numeric Patterns/numericpattern242.cpp
  Numeric Patterns/numericpattern243.cpp
  Numeric Patterns/numericpattern244.cpp
Labels: SWoC-21, easy

#965 Alphabetic and Numeric patterns
  Alphabetic Patterns/alphabeticpattern132.cpp
  Alphabetic Patterns/alphabeticpattern133.cpp
  Alphabetic Patterns/alphabeticpattern146.cpp
  Alphabetic Patterns/alphabeticpattern66.cpp
  Alphabetic Patterns/alphabeticpattern67.cpp
  Alphabetic Patterns/alphabeticpattern68.cpp
  Numeric Patterns/numericpattern274.cpp
  Numeric Patterns/numericpattern275.cpp
  Numeric Patterns/numericpattern315.cpp
  Numeric Patterns/numericpattern316.cpp
Labels: SWoC-21, beginner

#967 40 Patterns added
  Alphabetic Patterns/alphabeticpattern111.cpp
  Alphabetic Patterns/alphabeticpattern112.cpp
  Alphabetic Patterns/alphabeticpattern115.cpp
  Alphabetic Patterns/alphabeticpattern116.cpp
  Alphabetic Patterns/alphabeticpattern117.cpp
  Alphabetic Patterns/alphabeticpattern121.cpp
  Alphabetic Patterns/alphabeticpattern122.cpp
  Alphabetic Patterns/alphabeticpattern123.cpp
  Alphabetic Patterns/alphabeticpattern124.cpp
  Alphabetic Patterns/alphabeticpattern125.cpp
  Alphabetic Patterns/alphabeticpattern126.cpp
  Alphabetic Patterns/alphabeticpattern127.cpp
  Alphabetic Patterns/alphabeticpattern128.cpp
  Alphabetic Patterns/alphabeticpattern129.cpp
  Alphabetic Patterns/alphabeticpattern130.cpp
  Alphabetic Patterns/alphabeticpattern131.cpp
  Alphabetic Patterns/alphabeticpattern69.cpp
  Alphabetic Patterns/alphabeticpattern71.cpp
  Numeric Patterns/numericpattern264.cpp
  Numeric Patterns/numericpattern265.cpp
  Numeric Patterns/numericpattern266.cpp
  Numeric Patterns/numericpattern267.cpp
  Numeric Patterns/numericpattern268.cpp
  Numeric Patterns/numericpattern269.cpp
  Numeric Patterns/numericpattern270.cpp
  Numeric Patterns/numericpattern276.cpp
  Numeric Patterns/numericpattern277.cpp
  Numeric Patterns/numericpattern278.cpp
  Numeric Patterns/numericpattern279.cpp
  Numeric Patterns/numericpattern280.cpp
  Numeric Patterns/numericpattern281.cpp
  Numeric Patterns/numericpattern282.cpp
  Numeric Patterns/numericpattern284.cpp
  Numeric Patterns/numericpattern285.cpp
  Numeric Patterns/numericpattern289.cpp
  Numeric Patterns/numericpattern290.cpp
  Numeric Patterns/numericpattern291.cpp
  Numeric Patterns/numericpattern292.cpp
  Numeric Patterns/numericpattern293.cpp
  Numeric Patterns/numericpattern294.cpp
Labels: SWoC-21, hard

#968 Resolved Issue #917
  Series Patterns/seriespattern10.cpp
  Series Patterns/seriespattern11.cpp
  Series Patterns/seriespattern12.cpp
  Series Patterns/seriespattern13.cpp
  Series Patterns/seriespattern14.cpp
  Series Patterns/seriespattern15.cpp
  Series Patterns/seriespattern16.cpp
  Symbol Patterns/symbolpattern185.cpp
  Symbol Patterns/symbolpattern186.cpp
  Symbol Patterns/symbolpattern187.cpp
  Symbol Patterns/symbolpattern188.cpp
  Symbol Patterns/symbolpattern189.cpp
  Symbol Patterns/symbolpattern190.cpp
  Symbol Patterns/symbolpattern191.cpp
  Symbol Patterns/symbolpattern192.cpp
  Symbol Patterns/symbolpattern193.cpp
  Symbol Patterns/symbolpattern194.cpp
  Wave Patterns/wavepattern28.cpp
  Wave Patterns/wavepattern29.cpp
  Wave Patterns/wavepattern30.cpp
Labels: SWoC-21, easy

#966 Alphabetic Pattern 113, 114, 118-120, 303-306, 319.
  Alphabetic Patterns/alphabeticpattern113.cpp
  Alphabetic Patterns/alphabeticpattern114.cpp
  Alphabetic Patterns/alphabeticpattern118.cpp
  Alphabetic Patterns/alphabeticpattern119.cpp
  Alphabetic Patterns/alphabeticpattern120.cpp
  Numeric Patterns/numericpattern303.cpp
  Numeric Patterns/numericpattern304.cpp
  Numeric Patterns/numericpattern305.cpp
  Numeric Patterns/numericpattern306.cpp
  Numeric Patterns/numericpattern319.cpp
Labels: SWoC-21, beginner

#972 40 symbol patterns added
  Symbol Patterns/symbolpattern137.cpp
  Symbol Patterns/symbolpattern138.cpp
  Symbol Patterns/symbolpattern139.cpp
  Symbol Patterns/symbolpattern142.cpp
  Symbol Patterns/symbolpattern143.cpp
  Symbol Patterns/symbolpattern144.cpp
  Symbol Patterns/symbolpattern145.cpp
  Symbol Patterns/symbolpattern146.cpp
  Symbol Patterns/symbolpattern147.cpp
  Symbol Patterns/symbolpattern148.cpp
  Symbol Patterns/symbolpattern149.cpp
  Symbol Patterns/symbolpattern150.cpp
  Symbol Patterns/symbolpattern151.cpp
  Symbol Patterns/symbolpattern153.cpp
  Symbol Patterns/symbolpattern154.cpp
  Symbol Patterns/symbolpattern155.cpp
  Symbol Patterns/symbolpattern156.cpp
  Symbol Patterns/symbolpattern157.cpp
  Symbol Patterns/symbolpattern158.cpp
  Symbol Patterns/symbolpattern159.cpp
  Symbol Patterns/symbolpattern160.cpp
  Symbol Patterns/symbolpattern161.cpp
  Symbol Patterns/symbolpattern162.cpp
  Symbol Patterns/symbolpattern163.cpp
  Symbol Patterns/symbolpattern164.cpp
  Symbol Patterns/symbolpattern165.cpp
  Symbol Patterns/symbolpattern166.cpp
  Symbol Patterns/symbolpattern167.cpp
  Symbol Patterns/symbolpattern168.cpp
  Symbol Patterns/symbolpattern169.cpp
  Symbol Patterns/symbolpattern170.cpp
  Symbol Patterns/symbolpattern172.cpp
  Symbol Patterns/symbolpattern174.cpp
  Symbol Patterns/symbolpattern175.cpp
  Symbol Patterns/symbolpattern176.cpp
  Symbol Patterns/symbolpattern177.cpp
  Symbol Patterns/symbolpattern178.cpp
  Symbol Patterns/symbolpattern179.cpp
  Symbol Patterns/symbolpattern180.cpp
  Symbol Patterns/symbolpattern181.cpp
Labels: SWoC-21, hard

#973 Solved 12 issues
  Symbol Patterns/symbolpattern195.cpp
  Symbol Patterns/symbolpattern196.cpp
  Symbol Patterns/symbolpattern197.cpp
  Symbol Patterns/symbolpattern198.cpp
  Symbol Patterns/symbolpattern199.cpp
  Symbol Patterns/symbolpattern200.cpp
  Symbol Patterns/symbolpattern201.cpp
  Symbol Patterns/symbolpattern202.cpp
  Symbol Patterns/symbolpattern203.cpp
  Symbol Patterns/symbolpattern204.cpp
  Symbol Patterns/symbolpattern205.cpp
  Symbol Patterns/symbolpattern206.cpp
Labels: SWoC-21, beginner

#974 Added 26 patterns
  Numeric Patterns/numericpattern162.cpp
  Numeric Patterns/numericpattern227.cpp
  Numeric Patterns/numericpattern257.cpp
  Numeric Patterns/numericpattern258.cpp
  Numeric Patterns/numericpattern259.cpp
  Numeric Patterns/numericpattern295.cpp
  Numeric Patterns/numericpattern296.cpp
  Numeric Patterns/numericpattern297.cpp
  Numeric Patterns/numericpattern298.cpp
  Numeric Patterns/numericpattern299.cpp
  Numeric Patterns/numericpattern300.cpp
  Numeric Patterns/numericpattern301.cpp
  Numeric Patterns/numericpattern302.cpp
  Numeric Patterns/numericpattern307.cpp
  Numeric Patterns/numericpattern308.cpp
  Numeric Patterns/numericpattern309.cpp
  Numeric Patterns/numericpattern310.cpp
  Numeric Patterns/numericpattern312.cpp
  Numeric Patterns/numericpattern313.cpp
  Numeric Patterns/numericpattern320.cpp
  Numeric Patterns/numericpattern323.cpp
  Numeric Patterns/numericpattern325.cpp
  Numeric Patterns/numericpattern326.cpp
  Numeric Patterns/numericpattern327.cpp
  Symbol Patterns/symbolpattern182.cpp
  Symbol Patterns/symbolpattern183.cpp
  Symbol Patterns/symbolpattern184.cpp
Labels: SWoC-21, easy
